<div class="col-md-4 products-grid">
        <div class="products-number">
                  <p>[field:global.autoindex/].</p>
                </div>
        <div class="products-text">
                  <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                  <p>[field:description function="cn_substr(@me,200)"/]...</p>
                </div>
        <div class="clearfix"> </div>
      </div>