<div class="col-md-3 news-grid wow fadeInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;"> <a href="[field:arcurl/]" title="[field:title/]">
                <h4>[field:title/]...</h4>
                </a> <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span> <a href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]" /></a>
        <div class="news-info">
                  <p>[field:info/]...</p>
                </div>
      </div>