<div class="container">
    <div class="testimonial-nfo wow fadeInLeft animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
              <h3>[field:title/]</h3>
              <h5>Company honor</h5>
            </div>
    <div class="testimonial-grids wow fadeInRight animated" data-wow-delay="0.4s" style="visibility: visible; -webkit-animation-delay: 0.4s;">
              <div class="testimonial-grid">
        <p><span>"</span>[field:info/]...<span> "</span></p>
      </div>
              <div class="see-button"> <a class="btn btn-primary btn-lg see-button hvr-shutter-out-horizontal specialty-button" href="[field:arcurl/]" role="button">查看更多</a> </div>
            </div>
  </div>