<div class="blog-to">
        <div class="blog-top">
                  <div class="blog-left"> <b>[field:pubdate function="MyDate('d',@me)"/]</b> <span>[field:pubdate function="MyDate('Y-m',@me)"/]</span> </div>
                  <div class="top-blog"> <a class="fast" href="[field:arcurl/]">[field:title/]</a>
            <p class="sed">[field:description function="cn_substr(@me,400)"/]...</p>
            <a  href="[field:arcurl/]" class="more">查看详细<span> </span></a> </div>
                  <div class="clearfix"> </div>
                </div>
      </div>