<?php
$z[0]=Array("field","",189,208);
$z[0][4]['name']="title";
$z[1]=Array("global","",209,235);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",278,300);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",342,393);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",433,458);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n                  <li class=\"hvr-sweep-to-bottom\"><a href=\"[field:typeurl/]\">[field:typename/]<i><img src=\"/skin/images/nav-but[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global].png\" alt=\"\"/></i></a></li>\r\n                  ",2121,2579);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~<i><img src='/skin/images/nav-but2.png'/></i></a></li>";
$z[6]=Array("field","",3348,3396);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('d',@me)";
$z[7]=Array("field","",3407,3457);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m',@me)";
$z[8]=Array("field","",3527,3546);
$z[8][4]['name']="title";
$z[9]=Array("adminname","",3589,3606);
$z[10]=Array("field","",3629,3649);
$z[10][4]['name']="source";
$z[11]=Array("field","",3688,3706);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",3822,3847);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",4010,4036);
$z[13][4]['get']="next";
$z[14]=Array("include","",4286,4323);
$z[14][4]['filename']="footer.htm";

?>