<?php
$z[0]=Array("field","",189,208);
$z[0][4]['name']="title";
$z[1]=Array("global","",209,235);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",278,307);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",349,407);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",447,472);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n                  <li class=\"hvr-sweep-to-bottom\"><a href=\"[field:typeurl/]\">[field:typename/]<i><img src=\"/skin/images/nav-but[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global].png\" alt=\"\"/></i></a></li>\r\n                  ",2135,2593);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~<i><img src='/skin/images/nav-but3.png'/></i></a></li>";
$z[6]=Array("field","",35238,35259);
$z[6][4]['name']="content";
$z[7]=Array("include","",36425,36462);
$z[7][4]['filename']="footer.htm";

?>