<?php
$z[0]=Array("type","\r\n        <li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n        ",256,370);
$z[0][4]['typeid']="42";
$z[1]=Array("type","\r\n        <li><a href='[field:typelink/]'  rel='dropmenu2'>[field:typename/]</a></li>\r\n        ",380,510);
$z[1][4]['typeid']="43";
$z[2]=Array("type","\r\n        <li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n        ",520,634);
$z[2][4]['typeid']="44";
$z[3]=Array("type","\r\n        <li><a href='[field:typelink/]' >[field:typename/]</a></li>\r\n        ",644,758);
$z[3][4]['typeid']="45";
$z[4]=Array("global","",1579,1600);
$z[4][4]['name']="cfg_dz";
$z[5]=Array("global","",1658,1680);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        ",1929,2083);
$z[6][4]['sql']="Select content from dede_arctype where id=42";

?>