<?php
$z[0]=Array("global","",189,215);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",261,291);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",330,357);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",397,422);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n                  <li class=\"hvr-sweep-to-bottom\"><a href=\"[field:typeurl/]\">[field:typename/]<i><img src=\"/skin/images/nav-but[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global].png\" alt=\"\"/></i></a></li>\r\n                  ",2208,2666);
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~<i><img src='/skin/images/nav-but1.png'/></i></a></li>";
$z[5]=Array("field","",3673,3694);
$z[5][4]['name']="content";
$z[6]=Array("include","",3882,3919);
$z[6][4]['filename']="footer.htm";

?>