<?php
$z[0]=Array("field","",189,208);
$z[0][4]['name']="title";
$z[1]=Array("global","",209,235);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",278,307);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",349,407);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",447,472);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channel","\r\n                  <li class=\"hvr-sweep-to-bottom\"><a href=\"[field:typeurl/]\">[field:typename/]<i><img src=\"/skin/images/nav-but[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global].png\" alt=\"\"/></i></a></li>\r\n                  ",2137,2595);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~>~typename~<i><img src='/skin/images/nav-but2.png'/></i></a></li>";
$z[6]=Array("list","\r\n              <div class=\"col-md-4 products-grid\">\r\n        <div class=\"products-number\">\r\n                  <p>[field:global.autoindex/].</p>\r\n                </div>\r\n        <div class=\"products-text\">\r\n                  <h4><a href=\"[field:arcurl/]\">[field:title/]</a></h4>\r\n                  <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n                </div>\r\n        <div class=\"clearfix\"> </div>\r\n      </div>\r\n              ",3625,4113);
$z[6][4]['pagesize']="6";
$z[7]=Array("include","",4263,4300);
$z[7][4]['filename']="footer.htm";

?>