{dede:noteinfo notename="环保部官网环境要闻" channelid="1" macthtype="string"
refurl="http://www.zhb.gov.cn/xxgk/hjyw/index_2.shtml" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.zhb.gov.cn/xxgk/hjyw/index_(*).shtml"
startid="1" endid="10" addv="1" urlrule="area"
 musthas="title=" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="main_rt_list">
    	{/dede:areastart}
    {dede:areaend}<div class="page">{/dede:areaend}
{/dede:listrule}
