<?php
$z[0]=Array("arcurl","",21,36);
$z[0][4]=array();
$z[1]=Array("picname","",48,64);
$z[1][4]=array();
$z[2]=Array("title","",71,85);
$z[2][4]=array();
$z[3]=Array("arcurl","",135,150);
$z[3][4]=array();
$z[4]=Array("typelink","",152,169);
$z[4][4]=array();
$z[5]=Array("title","",170,184);
$z[5][4]=array();
$z[6]=Array("pubdate","",203,250);
$z[6][4]=array();
$z[6][4]['function']="GetDateTimeMK(@me)";

?>