<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",37,74);
$z[1][4]=array();
$z[1][4]['filename']="banner.htm";
$z[2]=Array("global","",220,247);
$z[2][4]=array();
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("channel","\r\n        <li>\r\n        		<a  href=\"[field:typelink/]\">[field:typename/]</a>\r\n        </li>\r\n        ",292,540);
$z[3][4]=array();
$z[3][4]['row']="7";
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a class='act'href='~typelink~' >~typename~</a> </li>";
$z[4]=Array("field","",747,773);
$z[4][4]=array();
$z[4][4]['name']="title";
$z[5]=Array("global","",774,807);
$z[5][4]=array();
$z[5][4]['name']="cfg_webname";
$z[6]=Array("field","",968,987);
$z[6][4]=array();
$z[6][4]['name']="title";
$z[7]=Array("field","",1032,1088);
$z[7][4]=array();
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[8]=Array("field","",2003,2021);
$z[8][4]=array();
$z[8][4]['name']="body";
$z[9]=Array("include","",2116,2153);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>