<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("type","\r\n	<img class=\"bannerIma\"style=\"text-align: center;\" src=\"/templets/test/images/fenyebanner14.jpg\" width=\"1343\"height=\"350\"  alt=\"[field:typename/]\" />\r\n	",133,310);
$z[1][4]=array();
$z[2]=Array("include","",4012,4050);
$z[2][4]=array();
$z[2][4]['filename']="footer.htm";

?>