<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("type","\r\n	<img class=\"bannerIma\"style=\"text-align: center;\" src=\"/templets/test/images/fenyebanner[field:id/].jpg\" width=\"1343\"height=\"350\"  alt=\"[field:typename/]\" />\r\n	",132,318);
$z[1][4]=array();
$z[2]=Array("field","",380,401);
$z[2][4]=array();
$z[2][4]['name']="content";
$z[3]=Array("include","",513,550);
$z[3][4]=array();
$z[3][4]['filename']="footer.htm";

?>