<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("type","\r\n	<img class=\"bannerIma\"style=\"text-align: center;\" src=\"/templets/test/images/fenyebanner14.jpg\" width=\"1343\"height=\"350\"  alt=\"[field:typename/]\" />\r\n	",138,315);
$z[1][4]=array();
$z[2]=Array("field","",599,622);
$z[2][4]=array();
$z[2][4]['name']="seotitle";
$z[3]=Array("field","",851,874);
$z[3][4]=array();
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",973,1002);
$z[4][4]=array();
$z[4][4]['name']="position";
$z[5]=Array("list","	\r\n                    <li ><span ><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></span><b>\r\n                    	<a href=\"[field:arcurl/]\">[field:typelink/]-[field:title/]</a></b><p></p><em>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n",1245,1568);
$z[5][4]=array();
$z[5][4]['pagesize']="20";
$z[6]=Array("pagelist","",1802,1852);
$z[6][4]=array();
$z[6][4]['istitem']="pre,next,";
$z[6][4]['listsize']="3";
$z[7]=Array("include","",1874,1911);
$z[7][4]=array();
$z[7][4]['filename']="footer.htm";

?>