<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("type","\r\n	<img class=\"bannerIma\"style=\"text-align: center;\" src=\"/templets/test/images/fenyebanner14.jpg\" width=\"1343\"height=\"350\"  alt=\"[field:typename/]\" />\r\n	",138,315);
$z[1][4]=array();
$z[2]=Array("channelartlist","\r\n        <li>\r\n        	<a  href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n        </li>\r\n        ",536,800);
$z[2][4]=array();
$z[2][4]['row']="2";
$z[2][4]['typeid']="31,32";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='act'>~typename~</a> </li>";
$z[3]=Array("field","",1000,1023);
$z[3][4]=array();
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",1122,1151);
$z[4][4]=array();
$z[4][4]['name']="position";
$z[5]=Array("list","	\r\n                    <li ><span ><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></span><b>\r\n                    	<a href=\"[field:arcurl/]\">[field:typelink/]-[field:title/]</a></b><p></p><em>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</em></li>\r\n",1394,1717);
$z[5][4]=array();
$z[5][4]['pagesize']="20";
$z[6]=Array("pagelist","",1951,2001);
$z[6][4]=array();
$z[6][4]['istitem']="pre,next,";
$z[6][4]['listsize']="3";
$z[7]=Array("include","",2023,2060);
$z[7][4]=array();
$z[7][4]['filename']="footer.htm";

?>