<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("type","\r\n		<img class=\"bannerIma\" style=\"text-align: center;\" src=\"/templets/test/images/fenyebanner12.jpg\" width=\"1343\" height=\"350\" alt=\"[field:typename/]\" /> ",133,310);
$z[1][4]=array();
$z[2]=Array("global","",632,659);
$z[2][4]=array();
$z[2][4]['name']="cfg_indexurl";
$z[3]=Array("include","",1981,2018);
$z[3][4]=array();
$z[3][4]['filename']="footer.htm";

?>